// Generated by nitro
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/pageview': {
      'default': Awaited<ReturnType<typeof import('../../server/api/pageview').default>>
    }
    '/__nuxt_error': {
      'default': Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@3.3.1_qcr72c723if2sxlfnbsa57v4m4/node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>
    }
  }
}
export {}